# example netlify.toml
[build]
  command = "nuxt generate"
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200

[dev]
  command = "npm run dev" # Command to start your dev server
  # port = 3000 # Port that the dev server will be listening on
  publish = "dist" # Folder with the static content for _redirect file

## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"